# Project identification
sonar.projectKey=finos-pylegend
sonar.organization=finos
sonar.projectName=PyLegend

#Python
sonar.python.version=3.13

# Source configuration
sonar.sources=.

# Test configuration
sonar.tests=./tests

# Encoding
sonar.sourceEncoding=UTF-8
