// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "!pQVQPOOOOQO'#C_'#C_OOQO'#Ca'#CaOOQO'#Cc'#CcOOQO'#Ce'#CeOOQO'#Cg'#CgOOQO'#Ci'#CiOOQO'#Ck'#CkOOQO'#Cm'#CmOOQO'#C^'#C^OOQO'#Co'#CoQVQPOOOOQO-E6m-E6m",
  stateData: "q~OfOS~OSPOUQOWROYSO[TO^UO`VObWO~O",
  goto: "sdPPeiPiPiPiPiPiPiPiPmTYOZTXOZQZOR[Z",
  nodeNames: "⚠ Program Statement KeywordStmt Keyword NewOneStmt1 NewOne1 NewOneStmt2 NewOne2 NewOneStmt3 NewOne3 NumberStmt Number OperatorStmt Operator IdentifierStmt Identifier ParensStmt Parens",
  maxTerm: 22,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: ":e~Rlqr!yst#Ouv#Txy#lyz#lz{!y{|!y}!O#q!P!Q!y![!]#y!^!_!y!_!`!y!`!a!y!f!g$P!}#O(Q#T#U,V#V#W-W#W#X/w#X#Y2p#Y#Z3`#Z#[4_#]#^6i#^#_,o#`#a6o#a#b7b#d#e7z#f#g8|#g#h9f~#OO^~~#TOU~~#WP#d#e#Z~#^P#i#j#a~#dP#h#i#g~#lOY~~#qOb~~#vP^~!`!a!y~#|P![!]!y~$SP#i#j$V~$YP#V#W$]~$`P#_#`$c~$fP!f!g$i~$lP#i#j$o~$rP#V#W$u~$xP#_#`${~%OR!e!f%X!f!g&f!t!u'b~%[P#c#d%_~%bP#b#c%e~%hP#b#c%k~%nP#X#Y%q~%tP#V#W%w~%zP#h#i%}~&QP#]#^&T~&WP#c#d&Z~&^P#b#c&a~&fOW~~&iP#T#U&l~&oP#h#i&r~&uP#T#U&x~&{P#U#V'O~'RP#T#U'U~'XP#g#h'[~'_P#X#Y&a~'eP#i#j'h~'kP#b#c'n~'qP#h#i't~'wP#]#^'z~'}P#a#b'[~(TRpq(^!Q!R)R#T#U)p~(aPXY(d~(gP]^(j~(mPYZ(p~(sP#P#Q(v~(yP{|(|~)ROf~~)UP}!O)X~)[P!Z![)_~)bP#P#Q)e~)hP{|)k~)pO[~~)sP}!O)v~)yP#n#o)|~*PP!c!d*S~*VP}!O*Y~*]P!|!}*`~*cP#P#Q*f~*iP!}#O*l~*oP#T#U*r~*uP}!O*x~*{P#n#o+O~+RP!c!d+U~+XP}!O+[~+_P!|!}+b~+eP!Q!R+h~+kP}!O+n~+qP!Z![+t~+wP#P#Q+z~+}Pz{,Q~,VO`~~,YP#g#h,]~,`P#c#d,c~,fP#Y#Z,i~,lP#^#_,o~,rP#c#d,u~,xP#]#^,{~-OP#b#c-R~-WOS~~-ZQ#`#a-a#c#d.o~-dP#X#Y-g~-jP#T#U-m~-pP#f#g-s~-vP#R#S-y~-|P#a#b.P~.SP#T#U.V~.YP#V#W.]~.`P#f#g.c~.fP#c#d.i~.lP#g#h#O~.rP#b#c.u~.xP#V#W.{~/OP#T#U/R~/UP#h#i/X~/[P#X#Y/_~/bP#b#c/e~/hP#T#U/k~/nP#h#i/q~/tP#X#Y-R~/zS#U#V#O#X#Y0W#]#^0^#f#g1S~0ZP#Y#Z-R~0aP#g#h0d~0gP#h#i0j~0mP#]#^0p~0sP#b#c0v~0yP#V#W0|~1PP#h#i-R~1VP#c#d1Y~1]P#d#e1`~1ePS~#R#S1h~1kP#T#U1n~1qP#`#a1t~1wP#`#a1z~1}P#R#S2Q~2TP#h#i2W~2ZP#T#U2^~2aP#U#V2d~2gP#`#a2j~2mP#X#Y.i~2sP#l#m2v~2yP#h#i2|~3PP#X#Y3S~3VP#b#c3Y~3]P#W#X-R~3cQ#]#^3i#f#g4R~3lP#`#a3o~3rP#h#i3u~3xP#X#Y3{~4OP#f#g-R~4UP#c#d4X~4[P#a#b-R~4bQ#X#Y4h#f#g5y~4kP#h#i4n~4qP#R#S4t~4wQ#T#U4}#h#i2W~5QP#h#i5T~5WP#h#i5Z~5^P#f#g5a~5dP#]#^5g~5jP#U#V5m~5pP#i#j5s~5vP#h#i2j~5|P#c#d6P~6SP#i#j6V~6YP#d#e6]~6`P!d!e6c~6fP#m#n-R~6lP#b#c#g~6rP#c#d6u~6xQ#T#U7O#V#W7U~7RP#W#X#O~7XP#T#U7[~7_P#`#a&a~7eP#T#U7h~7kP#V#W7n~7qP#f#g7t~7wP#c#d#O~7}Q#]#^8T#f#g8a~8WP#j#k8Z~8^P#c#d0|~8dQ#]#^8j#c#d8p~8mP#b#c0|~8sP#^#_8v~8yP#X#Y0v~9PP#X#Y9S~9VP#b#c9Y~9]P#T#U9`~9cP#a#b/q~9iS#X#Y9u#[#]9{#]#^:X#c#d:_~9xP#`#a8v~:OP#c#d:R~:UP#k#l-s~:[P#n#o/q~:bP#f#g0|",
  tokenizers: [0],
  topRules: {"Program":[0,1]},
  tokenPrec: 0
})
