# Copyright 2023 Goldman Sachs
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Setup Python, Setup Virtual Environment

description: Setup Python, Setup Virtual Environment

inputs:
  python-version:
    description: 'Python Version'
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Setup Virtual Environment
      run: |
        echo "Python version is:" $(python --version)
        echo "Creating and activating virtual environment"
        python -m venv .venv
        if [ "$RUNNER_OS" == "Windows" ]; then
          source .venv/Scripts/activate
        else
          source .venv/bin/activate
        fi
        echo "Done with activating virtual environment"
        echo "Python executable is:" $(which python)
        echo "Update pip and setuptools"
        python -m pip install --upgrade pip setuptools
        echo "Install poetry"
        pip install poetry
        echo "Setup complete"
      shell: bash
